version: "3.9"

services:
  twinbase-api:
    container_name: twinbase-api
    image: twinbase-api:1.0.0
    build:
      context: .
    environment:
      SECRET_KEY: ${TWINBASE_API_SECRET_KEY}
      HASHED_PASSWORD: ${TWINBASE_API_HASHED_PASSWORD}
      GITHUB_TOKEN: ${TWINBASE_API_GITHUB_TOKEN}
      OWNER_DID: ${TWINBASE_API_OWNER_DID}
      IAA_CONF_FILE: /iaa_config/iaa.conf
      PROXY_PASS: http://127.0.0.1:9000
    ports:
      - "8000:8000"
    volumes:
      - ./main.py:/code/main.py
      - iaa_config:/iaa_config
    command: uvicorn --host 0.0.0.0 --port 8000 --reload main:app

volumes:
  iaa_config: