FROM python:3.11-slim

# Set working directory
WORKDIR /code

# Update apt-get and install git, cleanup afterwards
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean

# Install Python requirements
COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt

# Copy necessary files
COPY iaa.py .

# Start app with uvicorn
CMD python iaa.py